export default [
  {
    id: 1,
    title: "The Godfather",
    img: "1.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 2,
    title: "Apocalypse Now",
    img: "2.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 3,
    title: "The Lord of the Rings",
    img: "3.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 4,
    title: "Gladiator",
    img: "4.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 5,
    title: "The Godfather",
    img: "5.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 6,
    title: "Apocalypse Now",
    img: "6.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 8,
    title: "The Lord of the Rings",
    img: "7.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 9,
    title: "The Lord of the Rings",
    img: "7.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    img: "7.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 11,
    title: "The Lord of the Rings",
    img: "7.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
  {
    id: 12,
    title: "The Lord of the Rings",
    img: "7.jpg",
    year: "2020",
    duree: "1h 40 min",
    genre: "Horreur/Action",
  },
];
